# -*- coding: utf-8 -*-
"""Dados_vendas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1hb4ANRHeUvGwBf1wHsdrb27xXBV_NF

# Análise de Dados: Dados Fictícios de Vendas em Rede de Clínicas Odontológicas #

* Olá! Os dados simulam transações de procedimentos dentários ao longo dos últimos 12 meses (de 18/09/2024 a 25/09/2024), com registros gerados aleatoriamente, mas de forma reproduzível (usando sementes para consistência).

*Os dados incluem:*

- Data: Data da venda (formato datetime).
- ID_Clinica: Identificador único da clínica (ex: CL01).
- Nome_Clinica: Nome da clínica (ex: Clínica Sorriso Norte).
- Tipo_Procedimento: Categoria do procedimento (ex: Consulta Inicial, Implante).
- Descricao_Procedimento: Descrição detalhada.
- Unidades_Vendidas: Quantidade de procedimentos realizados (1-3 por transação).
- Receita: Valor total da venda (Unidades × Preço unitário, arredondado para 2 casas decimais).
- ID_Paciente: Identificador único do paciente (ex: PAT000001).
"""

import pandas as pd

# Carregar CSVs
vendas = pd.read_csv('vendas_clinicas_odontologicas.csv', parse_dates=['Data'])
precos = pd.read_csv('tabela_precos.csv')

# Verificar dados
print("Vendas (primeiras 5 linhas):")
print(vendas.head())
print("\nTabela de Preços:")
print(precos)
print("\nInformações dos dados de vendas:")
print(vendas.info())

# Opcional: Juntar tabelas para validação
vendas_com_precos = vendas.merge(precos, on='Tipo_Procedimento', how='left')
print("\nValidação: Receita calculada (Unidades * Preço Unitário):")
print(vendas_com_precos[['Tipo_Procedimento', 'Unidades_Vendidas', 'Preco_Unitario', 'Receita']].head())

df.to_csv('vendas_clinicas_odontologicas.csv', index=False, sep=";")